Increment 22
vllvll/devops pull request #23
Opened 2022-10-09 09:27 UTC by vllvll

2022-10-13 07:44 UTC, Barugoo requested changes
Сделай, пожалуйста, PR в котором будут все диффы относящиеся к инкременту

2022-10-13 17:06 UTC, Barugoo commented on cmd/cert/main.go
> +	bitSize := 131072
Давай сделаем константой

2022-10-13 17:07 UTC, Barugoo commented on cmd/cert/main.go
> +		return
Мб здесь тоже `log.Fatal` тогда?

2022-10-13 19:33 UTC, Barugoo commented on internal/config/agent.go
> +		PollInterval:   "2s",
Вместо этого можем прописать тэг `default` в соответствующем поле в структуре

2022-10-13 19:34 UTC, Barugoo commented on cmd/server/main.go
>  			if err := httpServer.Shutdown(ctx); err != nil {
Я понял, у тебя graceful уже был реализован, оке

2022-10-13 20:03 UTC, Barugoo commented on internal/config/agent.go
> +	}
Не очень удобно, то что нам для каждого такого поля надо вот этот кусок кода писать.
Как вариант можно добавить тип-обертку над time.Duration и реализовать у нее метод UnmarshalJSON, в котором и делать time.ParseDuration
Соответственно при вызове json.Unmarshal время будет парсится автоматически

2022-10-13 20:05 UTC, Barugoo commented on internal/services/encrypt.go
> +func NewMetricEncrypt(path string) (Encrypt, error) {
А зачем мы делим этот функционал на encrypt/decrypt
Кажется, что у нас нет кейса, когда мы можем только шифровать, при этом не дешифруя, и наборот

2022-10-13 20:05 UTC, Barugoo approved these changes

2022-10-16 14:10 UTC, vllvll commented on internal/services/encrypt.go
> +func NewMetricEncrypt(path string) (Encrypt, error) {
encrypt вызывается в server, decrypt в agent и с разными параметрами. Только для этого

2022-10-16 14:14 UTC, vllvll commented on internal/config/agent.go
> +	}
хорошая идея, но будет выглядеть сверхнеобходимым функционалом для двух переменных конфига

2022-10-16 14:14 UTC, vllvll commented on cmd/server/main.go
>  			if err := httpServer.Shutdown(ctx); err != nil {
ок

2022-10-16 14:14 UTC, vllvll commented on cmd/cert/main.go
> +		return
ок

2022-10-16 14:14 UTC, vllvll commented on cmd/cert/main.go
> +	bitSize := 131072
ок

2022-10-16 14:19 UTC, merged