Increment 24
vllvll/devops pull request #25
Opened 2022-10-23 15:29 UTC by vllvll

2022-10-24 17:23 UTC, Barugoo commented on cmd/agent_grpc/main.go
> +	})
Круто, что ты пощупал язык шаблонов в Го, но кажется, что это оверинженеринг в данном случае
я бы просто сделал так:
```go
var (
    buildVersion string = "N/A"
//...
``` 
если в ldflags ничего не будет передано, то и значение в этих переменных глобальных останется то, которым ты их инициализировал

2022-10-24 18:03 UTC, Barugoo commented on proto/metric.proto
> +  string error = 1;
Кажется, что нам не нужна в теле респонса ошибка, мы ее возвращаем в любом случае
Можно просто в сигнатуре метода сделать `returns (google.protobuf.Empty)`

2022-10-24 18:06 UTC, Barugoo commented on proto/metric.proto
> +  }
Рекомендую добавлять дефолтный enum, тк в текущем виде у нас пустой MetricType (а ему соотвтествует значение по умолчанию для данного типа, то бишь - 0) нельзя отличить от Gauge
Обычно делают так:
```proto
enum Type {
    UNKNOWN = 0;
    GAUGE = 1;
    COUNTER = 2;
}
```

2022-10-24 18:08 UTC, Barugoo commented on proto/metric.proto
> +  Type m_type = 2;
я бы просто назвал поле `type`, мы его описываем внутри структуры Metric, очевидно что это тип метрики

2022-10-24 18:15 UTC, Barugoo commented on internal/services/grpc_send.go
> +	}
Кажется, что этой логике место в где-то поближе к функции в main
Тогда тебе не надо будет ее повторять для разных клиентов (grpc или resty)

2022-10-24 18:17 UTC, Barugoo commented on cmd/server_grpc/main.go
> +	var storeTick = time.Tick(config.StoreInterval)
Давай переместим это обьявление переменной поближе к месту, где мы ее первый раз используем

2022-10-24 18:17 UTC, Barugoo requested changes
Хорошо, но есть замечания

2022-10-25 17:43 UTC, vllvll commented on cmd/agent_grpc/main.go
> +
готово

2022-10-25 17:43 UTC, vllvll commented on proto/metric.proto
> +  string error = 1;
готово

2022-10-25 17:43 UTC, vllvll commented on proto/metric.proto
> +  }
готово

2022-10-25 17:43 UTC, vllvll commented on proto/metric.proto
> +  Type m_type = 2;
готово

2022-10-25 17:43 UTC, vllvll commented on internal/services/grpc_send.go
> +	}
готово

2022-10-25 17:43 UTC, vllvll commented on cmd/server_grpc/main.go
> +	var storeTick = time.Tick(config.StoreInterval)
готово

2022-10-27 16:00 UTC, Barugoo approved these changes
Работу принимаю

2022-12-24 09:57 UTC, merged